### ISSUE TITLE
Checkout button not working.

### ISSUE THREAD

**Issue by Erekoar221** [Sahil-kachhap/custom-phone-case-store#1]
![Screenshot_2024-06-28-09-13-32-480_com android chrome](https://github.com/Sahil-kachhap/custom-phone-case-store/assets/138151354/dd01d1fe-a541-4fcf-854f-c60faf43aca0)
![Screenshot_2024-06-28-09-13-24-499_com android chrome](https://github.com/Sahil-kachhap/custom-phone-case-store/assets/138151354/ca585482-2035-45dd-a9b3-718172ffa568)

This checkout button not getting clicked it do nothing.

**Comment by Sahil-kachhap** [comment]
@Erekoar221 payment gateway integration work is still under development right now. So I have kept it disabled intentionally. If you try it on desktop, you would be able to see a tooltip saying checkout is under development.
